### ISSUE TITLE
What games or applications are these for?

### ISSUE THREAD

**Issue by vashamamasha2014** [masterking32/MasterCryptoFarmBot#1]
What games or applications are these for?

**Comment by masterking32** [comment]
I have started working on a base project that allows you to manage all of your bots in one place. This project enables you to manage accounts, bots, and modules. You can add all your Telegram accounts to the project and install modules for different bots. This is just the foundation; we still need to develop additional modules for installation. For example: Blume, Not Pixel, etc modules.

**Comment by vashamamasha2014** [comment]
> Я начал работать над базовым проектом, который позволяет вам управлять всеми вашими ботами в одном месте. Этот проект позволяет вам управлять учетными записями, ботами и модулями. Вы можете добавить в проект все свои аккаунты Telegram и установить модули для разных ботов. Это только основа; нам все еще нужно разработать дополнительные модули для установки. Например: модули Blume, Not Pixel и др.
Интересный проект, но пока что вот так: 
![image](https://github.com/user-attachments/assets/2b42dcb2-14ae-4b5e-b96d-7bbe9df96646)
![image](https://github.com/user-attachments/assets/bb60be3c-a25c-4e8b-8f39-9ab2820d290a)

**Comment by masterking32** [comment]
> An interesting project, but for now this is how it is: ![image](https://private-user-images.githubusercontent.com/169598812/366408271-2b42dcb2-14ae-4b5e-b96d-7bbe9df96646.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNDk3NDksIm5iZiI6MTcyNjA0OTQ0OSwicGF0aCI6Ii8xNjk1OTg4MTIvMzY2NDA4MjcxLTJiNDJkY2IyLTE0YWUtNGI1ZS1iOTZkLTdiYmU5ZGY5NjY0Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMVQxMDEwNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZmRjYTI0ZDQwYzRlNzdiN2RhMGFkMTA0YzYzMDU3NmMzODExM2U1MGNmNDE2MWQ2NTMwNDc0OTMwOTYyZDlhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZJWs22sUgUOugknYDB7dgECr3i3hmt59aD7MTI3u0Lk) ![image](https://private-user-images.githubusercontent.com/169598812/366408429-bb60be3c-a25c-4e8b-8f39-9ab2820d290a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNDk3NDksIm5iZiI6MTcyNjA0OTQ0OSwicGF0aCI6Ii8xNjk1OTg4MTIvMzY2NDA4NDI5LWJiNjBiZTNjLWEyNWMtNGU4Yi04ZjM5LTlhYjI4MjBkMjkwYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMVQxMDEwNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NGUzNmZmMzM3NzljZGRkODA4NzM0OWM0YTJlZDE4YTBhNmM0ZDlhZWQxYzVkOTZkNjU0MzVkNTU1NzE3ODgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.t14l-8mlhy1aWuOgcBqZw1jq8pKVbZizU_jTorrVFKs)

It is under development and not finished yet!

**Comment by masterking32** [comment]
> > > An interesting project, but for now this is how it is: ![image](https://private-user-images.githubusercontent.com/169598812/366408271-2b42dcb2-14ae-4b5e-b96d-7bbe9df96646.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNDk3NDksIm5iZiI6MTcyNjA0OTQ0OSwicGF0aCI6Ii8xNjk1OTg4MTIvMzY2NDA4MjcxLTJiNDJkY2IyLTE0YWUtNGI1ZS1iOTZkLTdiYmU5ZGY5NjY0Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMVQxMDEwNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZmRjYTI0ZDQwYzRlNzdiN2RhMGFkMTA0YzYzMDU3NmMzODExM2U1MGNmNDE2MWQ2NTMwNDc0OTMwOTYyZDlhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZJWs22sUgUOugknYDB7dgECr3i3hmt59aD7MTI3u0Lk) ![image](https://private-user-images.githubusercontent.com/169598812/366408429-bb60be3c-a25c-4e8b-8f39-9ab2820d290a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNDk3NDksIm5iZiI6MTcyNjA0OTQ0OSwicGF0aCI6Ii8xNjk1OTg4MTIvMzY2NDA4NDI5LWJiNjBiZTNjLWEyNWMtNGU4Yi04ZjM5LTlhYjI4MjBkMjkwYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMVQxMDEwNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NGUzNmZmMzM3NzljZGRkODA4NzM0OWM0YTJlZDE4YTBhNmM0ZDlhZWQxYzVkOTZkNjU0MzVkNTU1NzE3ODgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.t14l-8mlhy1aWuOgcBqZw1jq8pKVbZizU_jTorrVFKs)
> > 
> > 
> > It is under development and not finished yet!
> 
> If you need any help, please let us know, maybe we can give you some advice or help speed up the development, we are very grateful to you for the best bot for Hamster)

Sure, Thanks.

**Comment by fastnfuriousbd** [comment]
Great man keep it up . I like your work if any help need from us let us know

**Comment by qawechi** [comment]
Ay e i can not help, but i am really greatful and thankful to your recent work (hamster). To you and all other people participated.

**Comment by Pawansingh333** [comment]
oh great thanks for this vey usefull bot

**Comment by marrsripon** [comment]
Till Now its look awesome . It is the best interface of bot

**Comment by cookie027** [comment]
> > > An interesting project, but for now this is how it is: ![image](https://private-user-images.githubusercontent.com/169598812/366408271-2b42dcb2-14ae-4b5e-b96d-7bbe9df96646.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNDk3NDksIm5iZiI6MTcyNjA0OTQ0OSwicGF0aCI6Ii8xNjk1OTg4MTIvMzY2NDA4MjcxLTJiNDJkY2IyLTE0YWUtNGI1ZS1iOTZkLTdiYmU5ZGY5NjY0Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMVQxMDEwNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZmRjYTI0ZDQwYzRlNzdiN2RhMGFkMTA0YzYzMDU3NmMzODExM2U1MGNmNDE2MWQ2NTMwNDc0OTMwOTYyZDlhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZJWs22sUgUOugknYDB7dgECr3i3hmt59aD7MTI3u0Lk) ![image](https://private-user-images.githubusercontent.com/169598812/366408429-bb60be3c-a25c-4e8b-8f39-9ab2820d290a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNDk3NDksIm5iZiI6MTcyNjA0OTQ0OSwicGF0aCI6Ii8xNjk1OTg4MTIvMzY2NDA4NDI5LWJiNjBiZTNjLWEyNWMtNGU4Yi04ZjM5LTlhYjI4MjBkMjkwYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMVQxMDEwNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NGUzNmZmMzM3NzljZGRkODA4NzM0OWM0YTJlZDE4YTBhNmM0ZDlhZWQxYzVkOTZkNjU0MzVkNTU1NzE3ODgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.t14l-8mlhy1aWuOgcBqZw1jq8pKVbZizU_jTorrVFKs)
> > 
> > 
> > It is under development and not finished yet!
> 
> If you need any help, please let us know, maybe we can give you some advice or help speed up the development, we are very grateful to you for the best bot for Hamster)

What kind of advice could you possibly give? You can't even figure out why this project isn't working. LOL

**Comment by Gusma-crypto** [comment]
for you continued success sir, and always be healthy, thank you for the hamstercombat code sir

**Comment by ParsapythonLv** [comment]
@masterking32 رفیق میشه بازی هایه مهم الان مثل cexio tap , blum , x empire و.. اضافه کنی
