### ISSUE TITLE
No module named "psutil"

### ISSUE THREAD

**Issue by qawechi** [masterking32/MasterCryptoFarmBot#19]
![Screenshot_2024-09-24-09-02-42-644_com.server.auditor.ssh.client.jpg](https://github.com/user-attachments/assets/e19e1642-f840-454b-b626-b15149a3fd2c)

**Comment by Fy0urM** [comment]
Is it mcf or mcf module?

**Comment by Fy0urM** [comment]
or just run via `sh ./start_linux.sh`

**Comment by qawechi** [comment]
> pip install psutil

It worked. Thank you.
