### ISSUE TITLE
Update concerns.

### ISSUE THREAD

**Issue by qawechi** [masterking32/MasterCryptoFarmBot#21]
I updated the bot in the command line with this command:
```
git pull origin main
```

But in the gui it says updated nearly 45 minz ago. While i updated it 2 minz ago with the cmd line manually.

![Screenshot_2024-09-24-22-01-32-789_com.sec.android.app.sbrowser.jpg](https://github.com/user-attachments/assets/0a37a6e0-e76f-4f3e-a443-2ccb6b1006f6)

Is this okay?

**Comment by masterking32** [comment]
Yes, that's the main project update date.
