### ISSUE TITLE
Mistake in code

### ISSUE THREAD

**Issue by Zzoomrus** [masterking32/MasterCryptoFarmBot#29]
In `utils/modules_thread.py` on 161 string:
`python_executable = sys.executable()` — `sys.executable` return string, it's not callable.
Just `python_executable = sys.executable`
It prevents modules from start if venv is used without any error messages.

**Comment by masterking32** [comment]
> In `utils/modules_thread.py` on 161 string: `python_executable = sys.executable()` — `sys.executable` return string, it's not callable. Just `python_executable = sys.executable` It prevents modules from start if venv is used without any error messages.

Yeah, My bad, Thanks.
