### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by tboy1337** [masterking32/MasterCryptoFarmBot#30]
```
[MasterCryptoFarmBot] [17:19:41] [INFO] 🚀 Running all modules ...
[MasterCryptoFarmBot] [17:19:41] [INFO] 🚀 Python Executable for running modules: C:\Program Files\Python312\python.exe
[MasterCryptoFarmBot] [17:19:41] [INFO] 🚀 Running MCF_HamsterKombat module ...
[MasterCryptoFarmBot] [17:19:41] [INFO] ✅ 1 modules running!
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by Fy0urM** [comment]
why is python installed for all users and not for the current user?)

**Comment by tboy1337** [comment]
It was already like that from previously as i had issues getting python to work in PATH

**Comment by tboy1337** [comment]
this is why I requested project to be built into an executable

**Comment by Fy0urM** [comment]
just completely uninstall all versions of python and install 1 normally? by default python is installed for the current user in %userprofile%/AppData, and if I'm not mistaken there is even a checkbox to add Python to the system PATH. if you install Python from the website and not from microsoft store.

**Comment by tboy1337** [comment]
I tried that already, as i said I had issues getting python to work in path, maybe because im running windows as a non admin user, im not sure but no way im dealing with that mess again

**Comment by tboy1337** [comment]
seems like admin doesn't want any users for his bot, so many barriers to entry, like 90% wouldn't even install GIT imo and would just delete the bot...

**Comment by Fy0urM** [comment]
> seems like admin doesn't want any users for his bot, so many barriers to entry, like 90% wouldn't even install GIT imo and would just delete the bot...

99% of users in tg chat

**Comment by tboy1337** [comment]
Unbelievable, good luck getting any customers @masterking32, as it is there is absolutely no way I am paying for anything you produce with an attitude like that

**Comment by Fy0urM** [comment]
> Unbelievable, good luck getting any customers @masterking32, as it is there is absolutely no way I am paying for anything you produce with an attitude like that

You should check if there are any changes before you complain. I think this is a fix for your problem.
https://github.com/masterking32/MasterCryptoFarmBot/commit/cb751429be1c028dbce2bb2fe4c118249145e4a6

**Comment by masterking32** [comment]
> Unbelievable, good luck getting any customers @masterking32, as it is there is absolutely no way I am paying for anything you produce with an attitude like that

Are you serious? Closes cause fixed also commit linked: https://github.com/masterking32/MasterCryptoFarmBot/commit/cb751429be1c028dbce2bb2fe4c118249145e4a6
