### ISSUE TITLE
Proxy Issues

### ISSUE THREAD

**Issue by tboy1337** [masterking32/MasterCryptoFarmBot#31]
http proxy is still not working.  I’m using webshare paid static residential proxies with the correct username and password set.  Error is as followed:

http

```
[MasterCryptoFarmBot] [18:24:19] [MCF_HamsterKombat] [INFO] 🔧 MCF_HamsterKombat module is starting ...
[MasterCryptoFarmBot] [18:24:19] [MCF_HamsterKombat] [INFO] [Playground] 🤖 Starting Playground thread...
[MasterCryptoFarmBot] [18:24:19] [MCF_HamsterKombat] [INFO] 🔍 Checking for accounts ...
[MasterCryptoFarmBot] [18:24:19] [MCF_HamsterKombat] [INFO] 🖥️ Start processing  1 Pyrogram accounts ...
[MasterCryptoFarmBot] [18:24:19] [MCF_HamsterKombat] [INFO] 🤖 Running xxx account ...
[MasterCryptoFarmBot] [18:24:19] [MCF_HamsterKombat] [INFO] 🌍 Connecting to Pyrogram (xxx) session ...
Unable to connect due to network issues: Socket error: 407: Proxy Authentication Required

Unable to connect due to network issues: Socket error: 407: Proxy Authentication Required

Unable to connect due to network issues: Socket error: 407: Proxy Authentication Required

Connection failed! Trying again...
Unable to connect due to network issues: Socket error: 407: Proxy Authentication Required

Unable to connect due to network issues: Socket error: 407: Proxy Authentication Required

Unable to connect due to network issues: Socket error: 407: Proxy Authentication Required
```

**Comment by tboy1337** [comment]
Although `socks5` is working

**Comment by masterking32** [comment]
https://docs.pyrogram.org/topics/proxy

**Comment by tboy1337** [comment]
If http is not supported at all then it should state that in the wiki, currently it gives http examples https://github.com/masterking32/MasterCryptoFarmBot/wiki/Account-Proxy

**Comment by tboy1337** [comment]
Also socks4 seems to not be supported so it probably would be a good idea to state that too

**Comment by masterking32** [comment]
As I know HTTP/Socks4-5 proxies work fine for some people, In our panel we are verifying your proxy for our modules and we are supporting proxies, it looks like Pyrogram not support your proxies and you need to ask for help in the Pyrogram project, We cannot do anything about that, Cause that's dependency and you need to ask help from them. Overall It would be better to use socks5 private proxies.
