### ISSUE TITLE
Cannot update the bot

### ISSUE THREAD

**Issue by Pedram987** [masterking32/MasterCryptoFarmBot#34]
![Screenshot 2024-10-02 191739](https://github.com/user-attachments/assets/4ccf3e84-08f2-4ac3-9f34-6cf649f9094d)

Hello, is this just for me or is a temporary issue?

I also tried with vpn

**Comment by Fy0urM** [comment]
Try clone manually, `git clone https://github.com/masterking32/MasterCryptoFarmBot.git`

**Comment by Pedram987** [comment]
Thank you sir
