### ISSUE TITLE
Error processing Pyrogram account: 'NoneType' object has no attribute 'run'

### ISSUE THREAD

**Issue by Ashwin3454** [masterking32/MasterCryptoFarmBot#43]
MCF_PocketFi

<img width="685" alt="image" src="https://github.com/user-attachments/assets/49940224-0c6a-4968-85ab-a7dddb590c24">

**Comment by tboy1337** [comment]
ive got a similar error with blum

```
[MasterCryptoFarmBot] [10:13:58] [MCF_Blum] [INFO] 🟡 Renewing access token...
[MasterCryptoFarmBot] [10:14:17] [MCF_Blum] [INFO] 🟡  Unable to send request, retrying...
[MasterCryptoFarmBot] [10:14:45] [MCF_Blum] [ERROR] ⭕ xxx failed to get balance!
[MasterCryptoFarmBot] [10:15:00] [MCF_Blum] [ERROR] ⭕ xxx failed to get balance!
[MasterCryptoFarmBot] [10:15:19] [MCF_Blum] [ERROR] ⭕ 'NoneType' object has no attribute 'get' failed to login!
[MasterCryptoFarmBot] [10:15:19] [MCF_Blum] [ERROR] ⭕ xxx failed to login!
```

**Comment by masterking32** [comment]
> ive got a similar error with blum
> 
> ```
> [MasterCryptoFarmBot] [10:13:58] [MCF_Blum] [INFO] 🟡 Renewing access token...
> [MasterCryptoFarmBot] [10:14:17] [MCF_Blum] [INFO] 🟡  Unable to send request, retrying...
> [MasterCryptoFarmBot] [10:14:45] [MCF_Blum] [ERROR] ⭕ xxx failed to get balance!
> [MasterCryptoFarmBot] [10:15:00] [MCF_Blum] [ERROR] ⭕ xxx failed to get balance!
> [MasterCryptoFarmBot] [10:15:19] [MCF_Blum] [ERROR] ⭕ 'NoneType' object has no attribute 'get' failed to login!
> [MasterCryptoFarmBot] [10:15:19] [MCF_Blum] [ERROR] ⭕ xxx failed to login!
> ```

That's not similar. and that's totally clear `xxx failed to get balance` Check your connections and create an issue for Blum not everywhere.

**Comment by masterking32** [comment]
> MCF_PocketFi
> <img alt="image" width="685" src="https://private-user-images.githubusercontent.com/180084972/374803485-49940224-0c6a-4968-85ab-a7dddb590c24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NzA5ODgsIm5iZiI6MTcyODQ3MDY4OCwicGF0aCI6Ii8xODAwODQ5NzIvMzc0ODAzNDg1LTQ5OTQwMjI0LTBjNmEtNDk2OC04NWFiLWE3ZGRkYjU5MGMyNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOVQxMDQ0NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZDNkMDk1YTA0MDhmNjdiNWMxMzQyYjY0MzM0NGZiZjlkNTZmZGQ2NDQxY2Y5MGFhMDQyNTU1ODIxMGZkNDUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Gz6zqL9KkpTXXgB6OqsMgLlAGQ5BHxhGGTqbDMp8xzg">

Can you send a full line of the error?
