### ISSUE TITLE
internal server error 500 when trying to login locally

### ISSUE THREAD

**Issue by buzZbot-oc** [masterking32/MasterCryptoFarmBot#48]
set up everything as u said boss but i cant login ,, what am i doing wrong here

![Screenshot 2024-10-09 225226](https://github.com/user-attachments/assets/97ec8618-09de-4377-a219-d0a858dc9600)
![Screenshot 2024-10-09 225106](https://github.com/user-attachments/assets/991acd5b-956f-402d-bfba-dd7a878ac0a3)

**Comment by buzZbot-oc** [comment]
hey boss

**Comment by masterking32** [comment]
Update your project and test again.

**Comment by buzZbot-oc** [comment]
it says project is up to date already , maybe its my pc issue?

**Comment by masterking32** [comment]
issue template is not valid create issue like templates ...
