### ISSUE TITLE
MCF_NotPixel 420 Error

### ISSUE THREAD

**Issue by tboy1337** [masterking32/MasterCryptoFarmBot#49]
```
[MasterCryptoFarmBot] [14:59:52] [MCF_NotPixel] [ERROR] └─ ❌ Telegram says: [420 FLOOD_WAIT_X] - A wait of 74 seconds is required (caused by "contacts.ResolveUsername")
```

- OS: Windows 10 Pro x64
 - Browser: Firefox Default
 - Version: 1.5.1

**Comment by AmirhN1382** [comment]
This is related to telegram, some numbers (like Iranian numbers) usually get this error when joining channels that are growing rapidly (e.g: getting too many users recently)

**Comment by tboy1337** [comment]
Ah I see, maybe add that explanation to the bot?

**Comment by AmirhN1382** [comment]
it's not only related to not pixel, it's a general telegram thing. not sure where to add.

**Comment by tboy1337** [comment]
It would be much better for users if instead of seeing some error numbers which does not mean anything it could actually be a short description of what the error is and even some tips to resolve it, that way you would get less support requests.

**Comment by tboy1337** [comment]
I dont see you guys using WARNING in the log much now either, it seems to be mostly INFO and ERROR, maybe an idea to add some errors as WARNINGs also?
