### ISSUE TITLE
Waiting Not Required

### ISSUE THREAD

**Issue by tboy1337** [masterking32/MasterCryptoFarmBot#52]
I post this here and not a module repo only because it seems to apply to all MCF modules.  When you are running accounts in parallel the random wait before running next account is not needed as the accounts are using seperate proxies so you can not make the connection of the two accounts.  It only makes sense for these random waits when users are running accounts in serial.  Below is an example.  Sorry for the random characters in the example but I’m running the log file through powershell with `powershell.exe type -wait %USERPROFILE%\MasterCryptoFarmBot\modules\MCF_NotPixel\bot.log` and it doesn’t seem to like the emoji.

```
[MasterCryptoFarmBot] [15:59:28] [INFO] âŒ› Farming for xxx completed. Waiting for 62 seconds before running the next account...
[MasterCryptoFarmBot] [16:00:30] [INFO] âœ… Pyrogram/Telethon account xxx from group 48 has been processed.
[MasterCryptoFarmBot] [16:00:30] [INFO] ðŸ”š Group 48 with 1 accounts has been processed. Waiting for other groups' tasks to finish
[MasterCryptoFarmBot] [16:00:33] [INFO] âœ… Pyrogram/Telethon account xxx from group 47 has been processed.
[MasterCryptoFarmBot] [16:00:33] [INFO] ðŸ”š Group 47 with 1 accounts has been processed. Waiting for other groups' tasks to finish
[MasterCryptoFarmBot] [16:00:38] [INFO] âœ… All accounts and groups have been processed successfully. Waiting for the next check ...
[MasterCryptoFarmBot] [16:00:38] [INFO] ðŸ’¤ Checking again in 2700 seconds ...
```

 - OS: Windows 10 Pro x64
 - Browser: Firefox Default
 - Version: 1.5.1

**Comment by masterking32** [comment]
Issue template invalid, Thats fine

**Comment by tboy1337** [comment]
This is more a request I guess, please add the ability to change `Delay between accounts` in all modules like you can in MCF_Blum.
