### ISSUE TITLE
MCF_Seed

### ISSUE THREAD

**Issue by tboy1337** [masterking32/MasterCryptoFarmBot#71]
### 🔍 Is there an existing issue for this?

- [X] I have searched the existing issues

### 📚 Did you install according to the wiki?

Yes

### 🔧 Have you made any custom changes to the software?

No

### 📦 Is this issue about a module?

Yes

### 🚀 How did you run the software?

start_linux.sh

### 🖥️ Operating System

Debian

### 📝 OS Version

13

### 🐍 Python Version

3.12

### 🐍 Do you have multiple Python versions installed on your system?

No

### 🌐 Is this issue related to an HTTP error?

No

### 📡 Is this issue related to Pyrogram or Telethon?

No

### 🐛 Describe the bug

Seeing the below a few times, I think its the seed module but cant be sure.

### 🎯 Expected Behavior

More information than `None`.

### 🔄 Steps To Reproduce

Run the bot.

### 💬 Anything else?

```
2024-10-16 15:00:43 [MasterCryptoFarmBot] [15:00:43] [MCF_Seed] [INFO] 🟡 Bot verification is pending
2024-10-16 15:00:43 None
2024-10-16 15:00:43 [MasterCryptoFarmBot] [15:00:43] [MCF_Seed] [INFO] 🟡 xxx task Earn 5 Gems on Catia not supported...
```

### 📜 Installed Modules (comma-separated)

ALL MODULES

**Comment by masterking32** [comment]
Please read before and think a bit before creating an issue, "task Earn 5 Gems on Catia" HOW WE CAN EARN 5 GEMS ON CATIA?
