### ISSUE TITLE
Cats&Dogs - Not watching YouTube videos

### ISSUE THREAD

**Issue by romulobp** [masterking32/MasterCryptoFarmBot#86]
### 🔍 Is there an existing issue for this?

- [X] I have searched the existing issues

### 📚 Did you install according to the wiki?

Yes

### 🔧 Have you made any custom changes to the software?

Yes

### 📦 Is this issue about a module?

Yes

### 🚀 How did you run the software?

start_linux.sh

### 🖥️ Operating System

Ubuntu

### 📝 OS Version

22

### 🐍 Python Version

3

### 🐍 Do you have multiple Python versions installed on your system?

No

### 🌐 Is this issue related to an HTTP error?

No

### 📡 Is this issue related to Pyrogram or Telethon?

No

### 🐛 Describe the bug

Not watching YouTube videos

### 📜 Installed Modules (comma-separated)

ALL

**Comment by tboy1337** [comment]
ive noticed issues with cats and dogs too, it seems to fail every task it tries to do.

**Comment by masterking32** [comment]
Hello, Cats&Dogs module has been updated, Please update your module...
