### ISSUE TITLE
BLUM BOT NOT WORKING

### ISSUE THREAD

**Issue by Ashwin3454** [masterking32/MasterCryptoFarmBot#94]
### 🔍 Is there an existing issue for this?

- [X] I have searched the existing issues

### 📚 Did you install according to the wiki?

Yes

### 🔧 Have you made any custom changes to the software?

No

### 📦 Is this issue about a module?

Yes

### 🚀 How did you run the software?

using command line

### 🖥️ Operating System

Windows

### 📝 OS Version

Windows 11

### 🐍 Python Version

3.12

### 🐍 Do you have multiple Python versions installed on your system?

Yes

### 🌐 Is this issue related to an HTTP error?

No

### 📡 Is this issue related to Pyrogram or Telethon?

No

### 🐛 Describe the bug

please update the BLUM module

### 📜 Installed Modules (comma-separated)

MCF_module

**Comment by Fy0urM** [comment]
updated yesterday, update the module and restart the mcf
![Screenshot_20241216-175038648](https://github.com/user-attachments/assets/950c46df-2105-42f9-bab0-56b9829d7262)

**Comment by masterking32** [comment]
https://github.com/masterking32/MCF_Blum/issues/13
