### ISSUE TITLE
ERROR: No pyvenv.cfg file

### ISSUE THREAD

**Issue by Ashwin3454** [masterking32/MasterCryptoFarmBot#95]
The program worked a minutes ago. but after a recent auto update, it happened.
<img width="515" alt="image" src="https://github.com/user-attachments/assets/cd19b9ca-3d5a-4e66-97b3-479d0381632c" />

**Comment by masterking32** [comment]
It's not about MCF, Search your problem in Google.
https://stackoverflow.com/questions/61026458/no-pyvenv-cfg-file
