### ISSUE TITLE
Error when starting the bot

### ISSUE THREAD

**Issue by krishealty** [masterking32/MasterCryptoFarmBot#96]
### 🔍 Is there an existing issue for this?

- [X] I have searched the existing issues

### 📚 Did you install according to the wiki?

Yes

### 🔧 Have you made any custom changes to the software?

Yes

### 📦 Is this issue about a module?

Yes

### 🚀 How did you run the software?

start_linux.sh

### 🖥️ Operating System

Windows

### 📝 OS Version

latest

### 🐍 Python Version

latest

### 🐍 Do you have multiple Python versions installed on your system?

Yes

### 🌐 Is this issue related to an HTTP error?

Yes

### 📡 Is this issue related to Pyrogram or Telethon?

Yes

### 🐛 Describe the bug

![Screenshot_2024-12-27-18-26-01-29_84d3000e3f4017145260f7618db1d683](https://github.com/user-attachments/assets/2fa1cfe2-4aee-4bb3-b64d-bad0458686f7)

The bot is not working, ive install all the libraries

### 📜 Installed Modules (comma-separated)

MCF

**Comment by tboy1337** [comment]
Use [Docker](https://github.com/masterking32/MasterCryptoFarmBot/wiki/Installation-Guide#-docker-installation)

**Comment by masterking32** [comment]
Read WIKI:
https://github.com/masterking32/MasterCryptoFarmBot/wiki/Installation-Guide
